services:
  cm-damselfly:
    container_name: cm-damselfly
    pull_policy: missing
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - target: 8088
        published: 8088
        protocol: tcp
    image: cloudbaristaorg/cm-damselfly:latest
    volumes:
      # - ./.damselfly/lkvstore.db:/app/db/lkvstore.db:rw
      # - ./log/damselfly.log:/app/log/damselfly.log:rw
      - ./.damselfly/:/app/db/
      - ./log/:/app/log/
    network_mode: "host"
    environment:
      # - DAMSELFLY_ROOT=/app
      ## Set API access config
      # DAMSELFLY_API_ALLOW_ORIGINS (ex: https://cloud-barista.org,http://localhost:8080 or * for all)
      - DAMSELFLY_API_ALLOW_ORIGINS=*
      # Set DAMSELFLY_API_AUTH_ENABLED=true currently for basic auth for all routes (i.e., url or path)
      - DAMSELFLY_API_AUTH_ENABLED=true
      - DAMSELFLY_API_USERNAME=default
      - DAMSELFLY_API_PASSWORD=default
      # Set DAMSELFLY_SELF_ENDPOINT, to access Swagger API dashboard outside (Ex: export SELF_ENDPOINT=x.x.x.x:8056)
      - DAMSELFLY_SELF_ENDPOINT=localhost:8088
      ## Logger configuration
      # Set log file path (default logfile path: ./damselfly.log) 
      - DAMSELFLY_LOGFILE_PATH=/app/log/damselfly.log
      - DAMSELFLY_LOGFILE_MAXSIZE=10
      - DAMSELFLY_LOGFILE_MAXBACKUPS=3
      - DAMSELFLY_LOGFILE_MAXAGE=30
      - DAMSELFLY_LOGFILE_COMPRESS=false
      # Set log level, such as trace, debug info, warn, error, fatal, and panic
      - DAMSELFLY_LOGLEVEL=debug
      # Set log writer, such as file, stdout, or both
      - DAMSELFLY_LOGWRITER=both

      # Set DB file path
      - DAMSELFLY_LKVSTORE_PATH=/app/db/damselfly.db

      # Set execution environment, such as development or production
      - DAMSELFLY_NODE_ENV=development
      ## Set period for auto control goroutine invocation
      - DAMSELFLY_AUTOCONTROL_DURATION_MS=10000
    healthcheck: # for CM-Beetle
      test: [ "CMD", "curl", "-f", "http://localhost:8088/damselfly/readyz" ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s
