services:
  cm-damselfly:
    image: cloudbaristaorg/cm-damselfly:0.3.5
    container_name: cm-damselfly
    pull_policy: missing
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - target: 8088
        published: 8088
        protocol: tcp
    volumes:
      - ./container-volume/cb-damselfly-container/db/:/app/db/
      - ./container-volume/cb-damselfly-container/log/:/app/log/
    environment:
      - DAMSELFLY_ROOT=/app
      # - DAMSELFLY_API_ALLOW_ORIGINS=*
      # - DAMSELFLY_API_AUTH_ENABLED=true
      # - DAMSELFLY_API_USERNAME=default
      # - DAMSELFLY_API_PASSWORD=default
      # - DAMSELFLY_SELF_ENDPOINT=localhost:8088
      # - DAMSELFLY_LOGFILE_PATH=/app/log/damselfly.log
      # - DAMSELFLY_LOGFILE_MAXSIZE=1000
      # - DAMSELFLY_LOGFILE_MAXBACKUPS=3
      # - DAMSELFLY_LOGFILE_MAXAGE=30
      # - DAMSELFLY_LOGFILE_COMPRESS=false
      - DAMSELFLY_LOGLEVEL=debug
      # - DAMSELFLY_LOGWRITER=both
      # - DAMSELFLY_LKVSTORE_PATH=/app/db/damselfly.db
      # - DAMSELFLY_NODE_ENV=production
      # - DAMSELFLY_AUTOCONTROL_DURATION_MS=10000
    healthcheck: # for CM-Beetle
      test: [ "CMD", "curl", "-f", "http://localhost:8088/damselfly/readyz" ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s
