package modelschema

import (
	"encoding/json"
	"os"
	"reflect"
	"sort"
	"strings"
	"testing"
)

func sortedPropertyNames(def map[string]interface{}) []string {
	props, _ := def["properties"].(map[string]interface{})
	names := make([]string, 0, len(props))
	for name := range props {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func sortedRequired(def map[string]interface{}) []string {
	var names []string
	switch req := def["required"].(type) {
	case []interface{}:
		for _, r := range req {
			names = append(names, r.(string))
		}
	case []string:
		names = append(names, req...)
	}
	sort.Strings(names)
	return names
}

// TestSwaggerDefinitionsMatchSwag compares the generated definitions of the compiled-in imdl/smdl versions with the
// definitions generated by swag (api/swagger.json) for the same version.
func TestSwaggerDefinitionsMatchSwag(t *testing.T) {
	data, err := os.ReadFile("../../api/swagger.json")
	if err != nil {
		t.Skipf("api/swagger.json is not available: %v", err)
	}
	var spec struct {
		Definitions map[string]map[string]interface{} `json:"definitions"`
	}
	if err := json.Unmarshal(data, &spec); err != nil {
		t.Fatal(err)
	}

	cases := []struct {
		importPath, swagPrefix, typeName string
	}{
		{"github.com/cloud-barista/cm-beetle/imdl/on-premise-model", "onpremisemodel.", "OnpremInfra"},
		{"github.com/cloud-barista/cm-beetle/imdl/cloud-model", "cloudmodel.", "RecommendedInfra"},
		{"github.com/cloud-barista/cm-grasshopper/smdl", "softwaremodel.", "SourceGroupSoftwareProperty"},
		{"github.com/cloud-barista/cm-grasshopper/smdl", "softwaremodel.", "TargetGroupSoftwareProperty"},
	}
	for _, tc := range cases {
		t.Run(tc.typeName, func(t *testing.T) {
			pkg := loadLocalPackage(t, tc.importPath)
			defs := map[string]interface{}{}
			ref, err := pkg.AddSwaggerDefinitions(defs, tc.typeName, "test.")
			if err != nil {
				t.Fatal(err)
			}
			if ref["$ref"] != "#/definitions/test."+tc.typeName {
				t.Fatalf("unexpected root reference: %v", ref)
			}
			if _, err := json.Marshal(defs); err != nil {
				t.Fatal(err)
			}

			compared := 0
			for name, generated := range defs {
				swagDef, ok := spec.Definitions[tc.swagPrefix+strings.TrimPrefix(name, "test.")]
				if !ok {
					t.Errorf("definition %s is not in api/swagger.json", name)
					continue
				}
				genDef := generated.(map[string]interface{})
				if got, want := sortedPropertyNames(genDef), sortedPropertyNames(swagDef); !reflect.DeepEqual(got, want) {
					t.Errorf("%s properties\n got: %v\nwant: %v", name, got, want)
				}
				if got, want := sortedRequired(genDef), sortedRequired(swagDef); !reflect.DeepEqual(got, want) {
					t.Errorf("%s required\n got: %v\nwant: %v", name, got, want)
				}
				compared++
			}
			if compared < 5 {
				t.Fatalf("only %d definitions were compared", compared)
			}
		})
	}
}

func TestSwaggerDefinitionsSample(t *testing.T) {
	pkg, err := ParsePackage(map[string][]byte{"sample.go": []byte(testSource + `
const (
	KindA Kind = "a"
	KindB Kind = "b"
)

type WithEnum struct {
	// Kind of the thing
	Kind Kind ` + "`json:\"kind\" validate:\"required\"`" + `
	Root Root ` + "`json:\"root\"`" + `
}
`)})
	if err != nil {
		t.Fatal(err)
	}

	defs := map[string]interface{}{}
	if _, err := pkg.AddSwaggerDefinitions(defs, "WithEnum", "p."); err != nil {
		t.Fatal(err)
	}
	out, _ := json.Marshal(defs)
	got := string(out)
	for _, want := range []string{
		`"p.WithEnum":{"properties":{"kind":{"description":"Kind of the thing","enum":["a","b"],"type":"string"}`,
		`"required":["kind"]`,
		`"next":{"$ref":"#/definitions/p.Root"}`,
		`"created":{"format":"date-time","type":"string"}`,
		`"data":{"format":"byte","type":"string"}`,
		`"labels":{"additionalProperties":{"type":"string"},"type":"object"}`,
		`"note":{"type":"string"}`,
		`"id":{"type":"string"}`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("generated definitions do not contain %s\n%s", want, got)
		}
	}
	if strings.Contains(got, `"hidden"`) || strings.Contains(got, `"Ignored"`) {
		t.Errorf("unexported or ignored fields must not be generated\n%s", got)
	}
}
