basePath: /damselfly
definitions:
  onprem.CpuProperty:
    properties:
      architecture:
        example: x86_64
        type: string
      cores:
        description: Number of physical cores per CPU
        example: 18
        type: integer
      cpus:
        description: Number of physical CPUs (sockets)
        example: 2
        type: integer
      maxSpeed:
        description: Maximum speed in GHz
        example: 3.6
        type: number
      model:
        example: Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
        type: string
      threads:
        description: Number of logical CPUs (threads) per CPU with hyper-threading
          enabled
        example: 36
        type: integer
      vendor:
        example: GenuineIntel
        type: string
    required:
    - cores
    - cpus
    - threads
    type: object
  onprem.DiskProperty:
    properties:
      available:
        description: Unit GiB
        type: integer
      label:
        type: string
      totalSize:
        description: Unit GiB
        example: 1024
        type: integer
      type:
        description: SSD, HDD
        example: SSD
        type: string
      used:
        description: Unit GiB
        type: integer
    required:
    - label
    - totalSize
    - type
    type: object
  onprem.MemoryProperty:
    properties:
      available:
        description: Unit GiB
        type: integer
      totalSize:
        description: Unit GiB
        example: 128
        type: integer
      type:
        example: DDR4
        type: string
      used:
        description: Unit GiB
        type: integer
    required:
    - totalSize
    - type
    type: object
  onprem.NetworkInterfaceProperty:
    properties:
      ipv4CidrBlocks:
        description: IPv4 address with prefix length (e.g., 192.168.0.21/24), instead
          of inet addr, Bcast, and Mask
        items:
          type: string
        type: array
      ipv6CidrBlocks:
        description: IPv6 address with prefix length (e.g., "2001:db8::1/64")
        items:
          type: string
        type: array
      macAddress:
        description: MAC address
        type: string
      mtu:
        description: Maximum Transmission Unit (MTU) in bytes
        type: integer
      name:
        description: Interface name (e.g., eth0, ens01, enp0s3)
        type: string
      state:
        description: Interface state (e.g., UP, DOWN)
        type: string
    required:
    - name
    type: object
  onprem.NetworkProperty:
    properties:
      ipv4Networks:
        example:
        - 172.26.240.0/20
        items:
          type: string
        type: array
      ipv6Networks:
        description: TBD
        items:
          type: string
        type: array
    type: object
  onprem.OsProperty:
    properties:
      id:
        example: ubuntu
        type: string
      idLike:
        example: debian
        type: string
      name:
        example: Ubuntu
        type: string
      prettyName:
        description: Pretty name
        example: Ubuntu 22.04.3 LTS
        type: string
      version:
        description: Full version string
        example: 22.04.3 LTS (Jammy Jellyfish)
        type: string
      versionCodename:
        example: jammy
        type: string
      versionId:
        example: "22.04"
        type: string
    required:
    - prettyName
    type: object
  onprem.RouteProperty:
    properties:
      destination:
        description: Destination network, expressed in CIDR format
        type: string
      gateway:
        description: Gateway address to which packets are forwarded
        type: string
      interface:
        description: Network interface associated with the route
        type: string
      linkState:
        description: Link state of the route (e.g., UP, DOWN)
        type: string
      metric:
        description: Metric value indicating the priority of the route
        type: integer
      protocol:
        description: Protocol used to set the route (e.g., kernel, static)
        type: string
      scope:
        description: Scope of the route (e.g., global, link, host)
        type: string
      source:
        description: Optionally stores the source address (used for policy-based routing)
        type: string
    type: object
  onprem.ServerProperty:
    properties:
      cpu:
        $ref: '#/definitions/onprem.CpuProperty'
      dataDisks:
        items:
          $ref: '#/definitions/onprem.DiskProperty'
        type: array
      hostname:
        type: string
      interfaces:
        items:
          $ref: '#/definitions/onprem.NetworkInterfaceProperty'
        type: array
      memory:
        $ref: '#/definitions/onprem.MemoryProperty'
      os:
        $ref: '#/definitions/onprem.OsProperty'
      rootDisk:
        $ref: '#/definitions/onprem.DiskProperty'
      routingTable:
        items:
          $ref: '#/definitions/onprem.RouteProperty'
        type: array
    type: object
  pkg_api_rest_handler.MyModel:
    properties:
      id:
        type: integer
      name:
        type: string
      network:
        $ref: '#/definitions/onprem.NetworkProperty'
      servers:
        items:
          $ref: '#/definitions/onprem.ServerProperty'
        type: array
    required:
    - servers
    type: object
  pkg_api_rest_handler.ReqCreateModel:
    properties:
      id:
        type: integer
      name:
        type: string
      network:
        $ref: '#/definitions/onprem.NetworkProperty'
      servers:
        items:
          $ref: '#/definitions/onprem.ServerProperty'
        type: array
    required:
    - servers
    type: object
  pkg_api_rest_handler.ReqPatchModel:
    properties:
      id:
        type: integer
      name:
        type: string
      network:
        $ref: '#/definitions/onprem.NetworkProperty'
      servers:
        items:
          $ref: '#/definitions/onprem.ServerProperty'
        type: array
    required:
    - servers
    type: object
  pkg_api_rest_handler.ReqUpdateModel:
    properties:
      id:
        type: integer
      name:
        type: string
      network:
        $ref: '#/definitions/onprem.NetworkProperty'
      servers:
        items:
          $ref: '#/definitions/onprem.ServerProperty'
        type: array
    required:
    - servers
    type: object
  pkg_api_rest_handler.ResCreateModel:
    properties:
      network:
        $ref: '#/definitions/onprem.NetworkProperty'
      servers:
        items:
          $ref: '#/definitions/onprem.ServerProperty'
        type: array
    required:
    - servers
    type: object
  pkg_api_rest_handler.ResGetModel:
    properties:
      id:
        type: integer
      name:
        type: string
      network:
        $ref: '#/definitions/onprem.NetworkProperty'
      servers:
        items:
          $ref: '#/definitions/onprem.ServerProperty'
        type: array
    required:
    - servers
    type: object
  pkg_api_rest_handler.ResGetModels:
    properties:
      models:
        items:
          $ref: '#/definitions/pkg_api_rest_handler.MyModel'
        type: array
    type: object
  pkg_api_rest_handler.ResHTTPVersion:
    properties:
      message:
        type: string
    type: object
  pkg_api_rest_handler.ResPatchModel:
    properties:
      id:
        type: integer
      name:
        type: string
      network:
        $ref: '#/definitions/onprem.NetworkProperty'
      servers:
        items:
          $ref: '#/definitions/onprem.ServerProperty'
        type: array
    required:
    - servers
    type: object
  pkg_api_rest_handler.ResReadyz:
    properties:
      message:
        type: string
    type: object
  pkg_api_rest_handler.ResUpdateModel:
    properties:
      id:
        type: integer
      name:
        type: string
      network:
        $ref: '#/definitions/onprem.NetworkProperty'
      servers:
        items:
          $ref: '#/definitions/onprem.ServerProperty'
        type: array
    required:
    - servers
    type: object
info:
  contact:
    email: contact-to-cloud-barista@googlegroups.com
    name: API Support
    url: http://cloud-barista.github.io
  description: CM-Damselfly REST API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: CM-Damselfly REST API
  version: latest
paths:
  /httpVersion:
    get:
      consumes:
      - application/json
      description: Checks and logs the HTTP version of the incoming request to the
        server console.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg_api_rest_handler.ResHTTPVersion'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/pkg_api_rest_handler.ResHTTPVersion'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg_api_rest_handler.ResHTTPVersion'
      summary: Check HTTP version of incoming request
      tags:
      - '[Admin] System management'
  /model:
    get:
      consumes:
      - application/json
      description: Get a list of models.
      produces:
      - application/json
      responses:
        "200":
          description: (sample) This is a list of models
          schema:
            $ref: '#/definitions/pkg_api_rest_handler.ResGetModels'
        "404":
          description: model not found
          schema:
            type: object
      summary: Get a list of models
      tags:
      - '[API] Cloud Migration Models (TBD)'
    post:
      consumes:
      - application/json
      description: Create a new model with the given information.
      parameters:
      - description: model information
        in: body
        name: Model
        required: true
        schema:
          $ref: '#/definitions/pkg_api_rest_handler.ReqCreateModel'
      produces:
      - application/json
      responses:
        "201":
          description: (Sample) This is a sample description for success response
            in Swagger UI
          schema:
            $ref: '#/definitions/pkg_api_rest_handler.ResCreateModel'
        "400":
          description: Invalid Request
          schema:
            type: object
      summary: Create a new model
      tags:
      - '[API] Cloud Migration Models (TBD)'
  /model/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a model with the given information.
      parameters:
      - description: Model ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Model deletion successful
          schema:
            type: string
        "400":
          description: Invalid Request
          schema:
            type: object
        "404":
          description: Model Not Found
          schema:
            type: object
      summary: Delete a model
      tags:
      - '[API] Cloud Migration Models (TBD)'
    get:
      consumes:
      - application/json
      description: Get a specific model.
      parameters:
      - description: Model ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: (Sample) a model
          schema:
            $ref: '#/definitions/pkg_api_rest_handler.ResGetModel'
        "404":
          description: model not found
          schema:
            type: object
      summary: Get a specific model
      tags:
      - '[API] Cloud Migration Models (TBD)'
    patch:
      consumes:
      - application/json
      description: Patch a model with the given information.
      parameters:
      - description: Model ID
        in: path
        name: id
        required: true
        type: integer
      - description: Model information to update
        in: body
        name: Model
        required: true
        schema:
          $ref: '#/definitions/pkg_api_rest_handler.ReqPatchModel'
      produces:
      - application/json
      responses:
        "200":
          description: (Sample) This is a sample description for success response
            in Swagger UI
          schema:
            $ref: '#/definitions/pkg_api_rest_handler.ResPatchModel'
        "400":
          description: Invalid Request
          schema:
            type: object
        "404":
          description: Model Not Found
          schema:
            type: object
      summary: Patch a model
      tags:
      - '[API] Cloud Migration Models (TBD)'
    put:
      consumes:
      - application/json
      description: Update a model with the given information.
      parameters:
      - description: Model ID
        in: path
        name: id
        required: true
        type: integer
      - description: Model information to update
        in: body
        name: Model
        required: true
        schema:
          $ref: '#/definitions/pkg_api_rest_handler.ReqUpdateModel'
      produces:
      - application/json
      responses:
        "201":
          description: (Sample) This is a sample description for success response
            in Swagger UI
          schema:
            $ref: '#/definitions/pkg_api_rest_handler.ResUpdateModel'
        "400":
          description: Invalid Request
          schema:
            type: object
      summary: Update a model
      tags:
      - '[API] Cloud Migration Models (TBD)'
  /readyz:
    get:
      consumes:
      - application/json
      description: Check Damselfly is ready
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg_api_rest_handler.ResReadyz'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/pkg_api_rest_handler.ResReadyz'
      summary: Check Damselfly is ready
      tags:
      - '[Admin] System management'
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
